### PR TITLE
Add the website for 2009.fossasia.org

### PR DESCRIPTION
**Pull request by shubham-padia**
This PR intends to complete the mini-project at fossasia/labs.fossasia.org#139 
@mariobehling These files are for  the `2009.fossasia.org` website which was built upon `cordobo-theme-park-2` wordpress theme . [Click here](http://shubhamp.in/wp/) to see the replica of `2009.fossasia.org`  in action . The web archived site can also be viewed [here](https://web.archive.org/web/20120324000651/http://2009.gnome.asia/index.html).

### CODE REVIEW

**Comment by mariobehling** [comment]
Great job! Thank you.

**Comment by shubham-padia** [comment]
Happy to contribute 😄

**Comment by mariobehling** [comment]
So, I have set up the wordpress, but I do not see where you implemented the sidebar widgets. How did you create them? How can they be configured?

**Comment by mariobehling** [comment]
Ok, found it in the theme settings. I wonder how we can also get the Vietnamese content https://web.archive.org/web/20120406003120/http://2009.gnome.asia/index.html?lang=vi

**Comment by shubham-padia** [comment]
We can get the vietnamese content with the help of `qTranslate X`  plugin , while `q translate 3` was used in the old website . I have started working on the same. Forgot to mention this , but please do not update the theme from the wordpress dashboard , otherwise the changes made in the `sidebar.php` and `footer.php` present in the themes folder will be overrided. 

Also , press release pdfs have not been archived by the webarchive , so the links corresponding to them are broken.

**Comment by shubham-padia** [comment]
For the sidebar section , i would recommend you to directly edit `/wp-content/themes/cordobo-green-park-2/sidebar.php` which now only contains html code.

**Pull request merged**
